## Read the JSON file that you saved in ex02.

In [3]:
import pandas as pd
import numpy as np
import requests
df = pd.read_json("../data/auto.json")
pd.options.display.float_format = '{:.2f}'.format
df

        CarNumber  Refund    Fines    Make    Model
0    Y163O8161RUS       2  3200.00    Ford    Focus
1     E432XX77RUS       1  6500.00  Toyota    Camry
2     7184TT36RUS       1  2100.00    Ford    Focus
3    X582HE161RUS       2  2000.00    Ford    Focus
4    92918M178RUS       1  5700.00    Ford    Focus
..            ...     ...      ...     ...      ...
720  Y163O8161RUS       2  1600.00    Ford    Focus
721  M0309X197RUS       1 22300.00    Ford    Focus
722  O673E8197RUS       2   600.00    Ford    Focus
723  8610T8154RUS       1  2000.00    Ford    Focus
724  H419XE197RUS       2  8594.59  Toyota  Corolla

[725 rows x 5 columns]

## Enrich the dataframe using a sample from that dataframe.

In [7]:
cars = df[['CarNumber', 'Make', 'Model']].drop_duplicates()
sample_df = cars.sample(n=200, random_state = 21, replace=True).reset_index(drop=True)
sample_df['Refund'] = df['Refund'].sample(n=200, random_state=21, replace=True).reset_index(drop=True).values
sample_df['Fines'] = df['Fines'].sample(n=200,random_state=21, replace=True).reset_index(drop=True).values
concat_rows = pd.concat([df, sample_df], ignore_index=True)
concat_rows

        CarNumber  Refund    Fines        Make  Model
0    Y163O8161RUS       2  3200.00        Ford  Focus
1     E432XX77RUS       1  6500.00      Toyota  Camry
2     7184TT36RUS       1  2100.00        Ford  Focus
3    X582HE161RUS       2  2000.00        Ford  Focus
4    92918M178RUS       1  5700.00        Ford  Focus
..            ...     ...      ...         ...    ...
920   X782CO96RUS       1  2000.00        Ford  Focus
921  E79988152RUS       2   400.00        Ford  Focus
922  X582HE161RUS       1 12800.00        Ford  Focus
923  9594HY161RUS       2   800.00        Ford  Focus
924  K327T8197RUS       2  2200.00  Volkswagen   Golf

[925 rows x 5 columns]

In [8]:
concat_rows.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        925
dtype: int64

## Enrich the concat_rows dataframe with a new column containing generated data.

In [9]:
np.random.seed(21)
year = pd.Series(np.random.randint(1980,2020, size = len(concat_rows)))
fines = concat_rows
fines['Year'] = year
fines

        CarNumber  Refund    Fines        Make  Model  Year
0    Y163O8161RUS       2  3200.00        Ford  Focus  1989
1     E432XX77RUS       1  6500.00      Toyota  Camry  1995
2     7184TT36RUS       1  2100.00        Ford  Focus  1984
3    X582HE161RUS       2  2000.00        Ford  Focus  2015
4    92918M178RUS       1  5700.00        Ford  Focus  2014
..            ...     ...      ...         ...    ...   ...
920   X782CO96RUS       1  2000.00        Ford  Focus  1981
921  E79988152RUS       2   400.00        Ford  Focus  1992
922  X582HE161RUS       1 12800.00        Ford  Focus  2007
923  9594HY161RUS       2   800.00        Ford  Focus  2005
924  K327T8197RUS       2  2200.00  Volkswagen   Golf  1997

[925 rows x 6 columns]

## Enrich the dataframe with data from another dataframe.

In [10]:
surnames_data = pd.read_json("../../datasets/surname.json")
header = surnames_data.iloc[0] 
data = surnames_data.iloc[1:].reset_index(drop=True)  

surnames_df = pd.DataFrame(data.values, columns=header)
surnames_df
SURNAME = pd.Series(surnames_df['NAME'].sample(n=len(concat_rows), random_state = 21, replace=True).reset_index(drop=True))
owners = pd.concat([concat_rows['CarNumber'],SURNAME], axis=1)
owners.rename(columns={'NAME': 'SURNAME'}, inplace=True)
owners

        CarNumber     SURNAME
0    Y163O8161RUS  RICHARDSON
1     E432XX77RUS        ROSS
2     7184TT36RUS      MORGAN
3    X582HE161RUS      BAILEY
4    92918M178RUS       LOPEZ
..            ...         ...
920   X782CO96RUS  RICHARDSON
921  E79988152RUS       ALLEN
922  X582HE161RUS      TORRES
923  9594HY161RUS     MENDOZA
924  K327T8197RUS   HERNANDEZ

[925 rows x 2 columns]

In [11]:
new_rows_df = pd.DataFrame({'CarNumber':['A159ТЕRUS','В123ВАRUS','D292FRRUS', 'R273RERUS','D326RUS'],'Refund':[2,1,2,2,1], 'Fines':[1100,5000,4400,3000,2000],
                            'Make':['Toyota', 'Skoda', 'Ford',' Volkswagen','Ford'], 'Model':['Camry', 'Octavia','Focus', 'Polo','Focus'], 'Year':[2012,2016,2014,2018,2008]})
fines = pd.concat([fines,new_rows_df],ignore_index=True)
fines

        CarNumber  Refund   Fines         Make    Model  Year
0    Y163O8161RUS       2 3200.00         Ford    Focus  1989
1     E432XX77RUS       1 6500.00       Toyota    Camry  1995
2     7184TT36RUS       1 2100.00         Ford    Focus  1984
3    X582HE161RUS       2 2000.00         Ford    Focus  2015
4    92918M178RUS       1 5700.00         Ford    Focus  2014
..            ...     ...     ...          ...      ...   ...
925     A159ТЕRUS       2 1100.00       Toyota    Camry  2012
926     В123ВАRUS       1 5000.00        Skoda  Octavia  2016
927     D292FRRUS       2 4400.00         Ford    Focus  2014
928     R273RERUS       2 3000.00   Volkswagen     Polo  2018
929       D326RUS       1 2000.00         Ford    Focus  2008

[930 rows x 6 columns]

In [12]:
fines.count()

CarNumber    930
Refund       930
Fines        930
Make         930
Model        930
Year         930
dtype: int64

In [8]:
owners = owners.iloc[:-20]

In [9]:
new_owners = pd.DataFrame({'CarNumber':['G323XMRUS', 'A121ETRUS', 'H637OPRUS'], 'SURNAME':['JORDAN', 'JAMES', 'SCOTT']})
owners = pd.concat([owners, new_owners], ignore_index = True)
owners

        CarNumber     SURNAME
0    Y163O8161RUS  RICHARDSON
1     E432XX77RUS        ROSS
2     7184TT36RUS      MORGAN
3    X582HE161RUS      BAILEY
4    92918M178RUS       LOPEZ
..            ...         ...
903  89587X197RUS       SCOTT
904  H907YK197RUS  RICHARDSON
905     G323XMRUS      JORDAN
906     A121ETRUS       JAMES
907     H637OPRUS       SCOTT

[908 rows x 2 columns]

In [10]:
all_numbers = pd.merge(owners,fines, on='CarNumber', how='outer')#все номера
all_numbers

         CarNumber  SURNAME  Refund    Fines   Make    Model    Year
0     704687163RUS   BROOKS    2.00  1400.00   Ford    Focus 2004.00
1     704787163RUS    GOMEZ    2.00  2800.00   Ford    Focus 1992.00
2     704987163RUS   CARTER    2.00  8594.59   Ford    Focus 1985.00
3     705287163RUS  JIMENEZ    2.00  2000.00   Ford    Focus 1980.00
4     705387163RUS     WOOD    2.00   700.00   Ford    Focus 1987.00
...            ...      ...     ...      ...    ...      ...     ...
1954  Y973O8197RUS    MOORE    1.00 69600.00   Ford    Focus 2017.00
1955  Y973O8197RUS    GOMEZ    2.00  8594.59   Ford    Focus 2005.00
1956  Y973O8197RUS    GOMEZ    1.00 34800.00   Ford    Focus 2003.00
1957  Y973O8197RUS    GOMEZ    1.00 69600.00   Ford    Focus 2017.00
1958     В123ВАRUS      NaN    1.00  5000.00  Skoda  Octavia 2016.00

[1959 rows x 7 columns]

In [13]:
in_both_numbers = pd.merge(owners,fines, how='inner')
in_both_numbers

         CarNumber     SURNAME  Refund    Fines        Make  Model  Year
0     Y163O8161RUS  RICHARDSON       2  3200.00        Ford  Focus  1989
1     Y163O8161RUS  RICHARDSON       2  1600.00        Ford  Focus  1980
2     Y163O8161RUS  RICHARDSON       1 27000.00        Ford  Focus  2017
3     Y163O8161RUS  RICHARDSON       1   800.00        Ford  Focus  2004
4      E432XX77RUS        ROSS       1  6500.00      Toyota  Camry  1995
...            ...         ...     ...      ...         ...    ...   ...
2006  X582HE161RUS      TORRES       1 12800.00        Ford  Focus  2007
2007  9594HY161RUS     MENDOZA       1   300.00        Ford  Focus  1989
2008  9594HY161RUS     MENDOZA       2   800.00        Ford  Focus  2005
2009  K327T8197RUS   HERNANDEZ       2 20800.00  Volkswagen   Golf  2005
2010  K327T8197RUS   HERNANDEZ       2  2200.00  Volkswagen   Golf  1997

[2011 rows x 7 columns]

In [12]:
only_in_fines = fines.merge(owners, how='left')
only_in_fines

         CarNumber  Refund   Fines         Make    Model  Year     SURNAME
0     Y163O8161RUS       2 3200.00         Ford    Focus  1989  RICHARDSON
1     Y163O8161RUS       2 3200.00         Ford    Focus  1989     ROBERTS
2     Y163O8161RUS       2 3200.00         Ford    Focus  1989      BROOKS
3     Y163O8161RUS       2 3200.00         Ford    Focus  1989       LOPEZ
4      E432XX77RUS       1 6500.00       Toyota    Camry  1995        ROSS
...            ...     ...     ...          ...      ...   ...         ...
1951     A159ТЕRUS       2 1100.00       Toyota    Camry  2012         NaN
1952     В123ВАRUS       1 5000.00        Skoda  Octavia  2016         NaN
1953     D292FRRUS       2 4400.00         Ford    Focus  2014         NaN
1954     R273RERUS       2 3000.00   Volkswagen     Polo  2018         NaN
1955       D326RUS       1 2000.00         Ford    Focus  2008         NaN

[1956 rows x 7 columns]

In [13]:
only_in_owners = fines.merge(owners,how='right')
only_in_owners

         CarNumber  Refund    Fines    Make  Model    Year     SURNAME
0     Y163O8161RUS    2.00  3200.00    Ford  Focus 1989.00  RICHARDSON
1     Y163O8161RUS    2.00  1600.00    Ford  Focus 1980.00  RICHARDSON
2     Y163O8161RUS    1.00 27000.00    Ford  Focus 2017.00  RICHARDSON
3     Y163O8161RUS    1.00   800.00    Ford  Focus 2004.00  RICHARDSON
4      E432XX77RUS    1.00  6500.00  Toyota  Camry 1995.00        ROSS
...            ...     ...      ...     ...    ...     ...         ...
1949  H907YK197RUS    2.00  7100.00    Ford  Focus 2015.00  RICHARDSON
1950  H907YK197RUS    1.00  2500.00    Ford  Focus 2018.00  RICHARDSON
1951     G323XMRUS     NaN      NaN     NaN    NaN     NaN      JORDAN
1952     A121ETRUS     NaN      NaN     NaN    NaN     NaN       JAMES
1953     H637OPRUS     NaN      NaN     NaN    NaN     NaN       SCOTT

[1954 rows x 7 columns]

## Create a pivot table from the fines dataframe. It should look like this (the values are the sums of the fines), but with all the years. The values may be different for you.

In [14]:
pivot_table = fines.pivot_table(
    index=['Make', 'Model'],  # группировка по марке и модели
    columns='Year',           # годы становятся столбцами
    values='Fines',     # значения для агрегации
    aggfunc='sum',          # считаем количество штрафов
    fill_value=0              # заполняем нулями отсутствующие значения
)
pivot_table

Year                    1980      1981      1982     1983      1984      1985  \
Make        Model
 Volkswagen Polo        0.00      0.00      0.00     0.00      0.00      0.00
Audi                    0.00      0.00      0.00     0.00      0.00      0.00
BMW                     0.00      0.00      0.00     0.00      0.00      0.00
Ford        Focus   56489.17 398589.17 140383.76 62300.00 112494.59 189583.76
            Mondeo      0.00      0.00      0.00     0.00      0.00      0.00
Skoda       Octavia  1900.00      0.00   6900.00 11594.59      0.00  10294.59
Toyota      Camry   28500.00   8594.59      0.00  7200.00      0.00      0.00
            Corolla     0.00      0.00   2000.00   800.00      0.00      0.00
Volkswagen              0.00      0.00      0.00     0.00      0.00      0.00
            Golf    30900.00      0.00      0.00  8594.59    300.00  24000.00
            Jetta       0.00      0.00      0.00     0.00      0.00      0.00
            Passat   6500.00   1600.00      0.00  3200.00  10000.00   5000.00
            Touareg     0.00      0.00      0.00     0.00      0.00   5800.00
Volvo                   0.00      0.00   6800.00     0.00      0.00      0.00

Year                     1986      1987     1988      1989  ...      2010  \
Make        Model                                           ...
 Volkswagen Polo         0.00      0.00     0.00      0.00  ...      0.00
Audi                     0.00      0.00     0.00      0.00  ...      0.00
BMW                      0.00  10600.00     0.00      0.00  ...      0.00
Ford        Focus   104994.59 132800.00 95489.17 125700.00  ... 120183.76
            Mondeo       0.00      0.00     0.00   8600.00  ...      0.00
Skoda       Octavia    600.00   5200.00   500.00  91400.00  ...   3100.00
Toyota      Camry        0.00      0.00     0.00  22400.00  ...      0.00
            Corolla      0.00   8000.00     0.00   4000.00  ...  24000.00
Volkswagen            7400.00      0.00     0.00      0.00  ...      0.00
            Golf         0.00   9300.00     0.00   5800.00  ...      0.00
            Jetta        0.00      0.00     0.00      0.00  ...      0.00
            Passat   15000.00  12300.00     0.00      0.00  ...   2800.00
            Touareg      0.00      0.00     0.00      0.00  ...   6300.00
Volvo                    0.00      0.00     0.00      0.00  ...      0.00

Year                    2011      2012      2013      2014      2015     2016  \
Make        Model
 Volkswagen Polo        0.00      0.00      0.00      0.00      0.00     0.00
Audi                    0.00      0.00      0.00      0.00      0.00     0.00
BMW                     0.00   3000.00      0.00      0.00   8594.59     0.00
Ford        Focus   86689.17 120200.00 149294.59 161894.59 210789.17 83694.59
            Mondeo      0.00  34400.00      0.00      0.00      0.00 48100.00
Skoda       Octavia   500.00    500.00  19594.59   3300.00  46394.59  5300.00
Toyota      Camry    3300.00  11694.59      0.00      0.00      0.00     0.00
            Corolla  8594.59      0.00      0.00      0.00      0.00     0.00
Volkswagen              0.00      0.00      0.00      0.00      0.00     0.00
            Golf      300.00      0.00      0.00      0.00   2300.00     0.00
            Jetta       0.00      0.00      0.00      0.00      0.00     0.00
            Passat      0.00      0.00      0.00      0.00    600.00  2100.00
            Touareg     0.00      0.00      0.00   1300.00    500.00     0.00
Volvo                   0.00      0.00      0.00      0.00   1500.00     0.00

Year                     2017      2018      2019
Make        Model
 Volkswagen Polo         0.00   3000.00      0.00
Audi                     0.00      0.00      0.00
BMW                      0.00   6500.00      0.00
Ford        Focus   268200.00 283594.59 117100.00
            Mondeo       0.00      0.00      0.00
Skoda       Octavia   4000.00 156200.00   9500.00
Toyota      Camry     1000.00  13000.00  18100.00
            Corolla   9600.00      0.00      0.00
Volkswagen               0.00      0.00      0.00
            Golf         0.00      0.00      0.00
            Jetta        0.00      0.00      0.00
            Passat       0.00      0.00      0.00
            Touareg      0.00      0.00      0.00
Volvo                    0.00   1600.00  10200.00

[14 rows x 40 columns]

In [15]:
concat_rows.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        925
Year         925
dtype: int64

In [16]:
len(owners)

908

In [17]:
len(fines)

930

In [26]:
fines.to_csv('../data/fines.csv')
owners.to_csv('../data/owners.csv')