## read_csv

In [1]:
import pandas as pd
df = pd.read_csv("../data/feed-views.log", 
                sep='\t',
                skiprows = [2,3],
                skipfooter=2,
                names=['datetime', 'user'],
                engine='python',
                index_col='datetime')
df

                                 user
datetime
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

## Rename datetime to date_time

In [2]:
df.index.name = 'date_time'

In [3]:
df.count()

user    1072
dtype: int64

In [4]:
df2 = pd.read_csv("../data/feed-views-semicolon.log", sep=';')

In [5]:
df2.head()

                    date_time    user
0  2020-04-17 12:01:08.463179   artem
1  2020-04-17 12:01:23.743946   artem
2  2020-04-17 12:35:52.735016   artem
3  2020-04-17 12:36:21.401412  oksana
4  2020-04-17 12:36:22.023355  oksana

## to_csv

In [6]:
df.to_csv('../data/feed-views-semicolon.log', sep=';')