## Load the JSON file that you created in the previous exercise into a dataframe.

In [1]:
import pandas as pd
df = pd.read_json("../data/auto.json")
df = df.set_index('CarNumber')

## Make the following selections:

In [2]:
df[(df['Fines']>2100)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]

In [4]:
df.groupbycount()

Refund    725
Fines     725
Make      725
Model     725
dtype: int64

In [28]:
df[(df['Fines']>2100) & (df['Refund']==2)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

In [29]:
models = ['Focus', 'Corolla']
df[(df['Model'].isin(models))]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

In [2]:
df.groupby(['Make', 'Model']).agg('Fines').count()

Make        Model
Audi                     1
BMW                      3
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen               3
            Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Volvo                    2
Name: Fines, dtype: int64

In [37]:
numbers = ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
df[df.index.isin(numbers)]

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

## Make the aggregations with the make and model.

In [40]:
df.groupby('Model')['Fines'].median()

Model
           6800.0
Camry      7700.0
Corolla    7700.0
Focus      3500.0
Golf       4800.0
Jetta      2800.0
Mondeo     7650.0
Octavia    3250.0
Passat     3500.0
Touareg    5800.0
Name: Fines, dtype: float64

In [41]:
df.groupby(['Make','Model'])['Fines'].median()

Make        Model
Audi                   4200.0
BMW                    6500.0
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen             7400.0
            Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Volvo                  8500.0
Name: Fines, dtype: float64

In [42]:
df.groupby('Make')['Fines'].median()

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

In [5]:
df.groupby(['Make', 'Model']).agg('Fines').count()

Make        Model
Audi                     1
BMW                      3
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen               3
            Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Volvo                    2
Name: Fines, dtype: int64

In [43]:
df.groupby(['Make','Model'])['Fines'].agg('count')

Make        Model
Audi                     1
BMW                      3
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen               3
            Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Volvo                    2
Name: Fines, dtype: int64

In [44]:
df.groupby(['Make','Model'])['Fines'].max()

Make        Model
Audi                     4200.000000
BMW                      8594.586466
Ford        Focus      180000.000000
            Mondeo      46200.000000
Skoda       Octavia    145000.000000
Toyota      Camry       22400.000000
            Corolla     34300.000000
Volkswagen               7900.000000
            Golf       168000.000000
            Jetta       46000.000000
            Passat      29700.000000
            Touareg      8594.586466
Volvo                   10200.000000
Name: Fines, dtype: float64

In [45]:
df.groupby(['Make','Model'])['Fines'].min()

Make        Model
Audi                   4200.0
BMW                    3000.0
Ford        Focus       100.0
            Mondeo     1100.0
Skoda       Octavia     300.0
Toyota      Camry       500.0
            Corolla     900.0
Volkswagen             1300.0
            Golf        200.0
            Jetta       500.0
            Passat      100.0
            Touareg     500.0
Volvo                  6800.0
Name: Fines, dtype: float64

In [46]:
df.groupby(['Make','Model'])['Fines'].std()

Make        Model
Audi                            NaN
BMW                     2826.561226
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen              3674.688195
            Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Volvo                   2404.163056
Name: Fines, dtype: float64

In [3]:
df.groupby('CarNumber')['Fines'].count().sort_values(ascending=False)

CarNumber
Y7689C197RUS    4
7788KT197RUS    4
92928M178RUS    4
Y7129Y50RUS     3
X758HY197RUS    3
               ..
Y967O8197RUS    1
Y965O8197RUS    1
Y965EE197RUS    1
Y964O8197RUS    1
Y964EE197RUS    1
Name: Fines, Length: 531, dtype: int64

In [54]:
most_count = df.groupby('CarNumber')['Fines'].count().sort_values(ascending=False).index[0]
df[df.index==most_count]

              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS       1  27000.0  Ford  Focus
Y7689C197RUS       2   9000.0  Ford  Focus
Y7689C197RUS       2  45000.0  Ford  Focus
Y7689C197RUS       1  36000.0  Ford  Focus

In [55]:
df.groupby('CarNumber')['Fines'].sum().sort_values(ascending=False)

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
Y166O8161RUS       100.0
K326T8197RUS       100.0
Y195O8161RUS       100.0
C58078163RUS       100.0
705787163RUS       100.0
Name: Fines, Length: 531, dtype: float64

In [56]:
most_sum = df.groupby('CarNumber')['Fines'].sum().sort_values(ascending=False).index[0]
df[df.index==most_sum]

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

In [57]:
duplicate_nums = df.groupby('CarNumber')['Model'].nunique()
conflicts = duplicate_nums[duplicate_nums > 1]
new_df = pd.DataFrame(duplicate_nums)
new_df.columns = ['Num_Count']
new_df.sort_values('Num_Count', ascending = False)

              Num_Count
CarNumber
E316EH197RUS          2
704787163RUS          1
704987163RUS          1
705287163RUS          1
705387163RUS          1
...                 ...
Y965O8197RUS          1
Y966O8197RUS          1
Y967O8197RUS          1
Y969O8197RUS          1
Y973O8197RUS          1

[531 rows x 1 columns]

In [58]:
df.groupby(['CarNumber','Make'])['Model'].nunique().sort_values(ascending=False)

CarNumber     Make
E316EH197RUS  Volkswagen    2
704787163RUS  Ford          1
704987163RUS  Ford          1
705287163RUS  Ford          1
705387163RUS  Ford          1
                           ..
Y965O8197RUS  Ford          1
Y966O8197RUS  Ford          1
Y967O8197RUS  Ford          1
Y969O8197RUS  Ford          1
Y973O8197RUS  Ford          1
Name: Model, Length: 531, dtype: int64